# Generated by Django 2.2.5 on 2020-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseentry',
            name='lat_long',
            field=models.CharField(default=42.1212, max_length=500),
            preserve_default=False,
        ),
    ]
