# Generated by Django 2.2.5 on 2020-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0002_diseaseentry_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseentry',
            name='deaths',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
